- name: Launch instance for Kubernetes Master
  ec2_instance:
    region: "ap-south-1"
    image_id: "ami-08e0ca9924195beba"
    instance_type: "t2.micro"
    vpc_subnet_id: "subnet-dde89791"
    name: "k8s-master"
    security_group: "sg-ddd604ba"
    key_name: "awskey"
    aws_access_key:  "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    state: present
  register: master

- name: Launch instance for Kubernetes worker node 
  ec2_instance:
    region: "ap-south-1"
    image_id: "ami-08e0ca9924195beba"
    instance_type: "t2.micro"
    vpc_subnet_id: "subnet-dde89791"
    name: "k8s-node1"
    security_group: "sg-ddd604ba"
    key_name: "awskey"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    state: present
  register: node1
- name: Launch instance for Kubernetes worker node
  ec2_instance:
    region: "ap-south-1"
    image_id: "ami-08e0ca9924195beba"
    instance_type: "t2.micro"
    vpc_subnet_id: "subnet-dde89791"
    name: "k8s-node2"
    security_group: "sg-ddd604ba"
    key_name: "awskey"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    state: present
  register: node2
  
- name: Updating ansible inventory for k8s cluster
  blockinfile:
    path: /etc/ansible/hosts
    block: |
      [master]
        {{  master.instances[0].public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/awskey.pem

      [node]

        {{  node1.instances[0].public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/awskey.pem

        {{  node2.instances[0].public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/awskey.pem



